version: 2.1

aliases:
  - &runner
    executor:
      name: node/default
      tag: << parameters.node-version >>
  - &size
    resource_class: small
  - &params
    parameters:
      node-version:
        type: string

orbs:
  node: circleci/node@5
  slack: circleci/slack@4
  codecov: codecov/codecov@3

jobs:
  lint:
    <<: *runner
    <<: *size
    <<: *params
    steps:
      - checkout
      - &restore-cache
        restore_cache:
          keys:
            # Caching node_modules means we can't share it across node versions
            - &cache-key node-deps-{{ arch }}-<< parameters.node-version >>-{{ checksum "package.json" }}
      - &install
        run: npm install # no npm ci, because no package-lock.json, because this is a lbirary
      - &save-cache
        save_cache:
          key: *cache-key
          paths:
            - node_modules # yes, really
      - run: npm run lint:prettier
      - run: npm run lint:eslint -- --format junit --output-file reports/eslint/results.xml
  test:
    <<: *runner
    <<: *size
    <<: *params
    steps:
      - checkout
      - *restore-cache
      - *install
      - *save-cache
      - run: npm test -- --ci --coverage # reports automatically generated

workflows:
  build:
    jobs:
      - lint:
          node-version: lts
          post-steps:
            - &retrieve-junit
              store_test_results:
                path: reports
      - test:
          context: shared-vars
          requires:
            - lint
          matrix:
            parameters:
              node-version:
                - lts
                - current
          post-steps:
            - *retrieve-junit
            - codecov/upload # don't need token for public repos
            - slack/notify:
                event: fail
                template: basic_fail_1
